apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dongtai-docs
  name: dongtai-docs
  namespace: iast-prod
spec:
  selector:
    matchLabels:
      app: dongtai-docs
  template:
    metadata:
      labels:
        app: dongtai-docs
    spec:
      containers:
      - image: dongtai/dongtai-docs:VERSION
        imagePullPolicy: Always
        name: dongtai-docs
        env:
        - name: aliyun_logs_iast_server_project
          value: k8s-log-c541e7d8ffff2434a8b7b4fd7d8645d2a
        - name: aliyun_logs_iast_server
          value: stdout